Only copy code if not hidden
beemdevelopment/Aegis pull request #1016
Opened 2022-11-02 20:50 UTC by orange-elephant

#690

2022-11-06 11:36 UTC, alexbakker requested changes
Neat! One small nitpick and issue though.

Some entries seem to stay dimmed after highlighting and copying. To reproduce:
- Enable tap to reveal, highlight on tap and copy on tap.
- Have an entry list bigger than the size of the screen, so that you have to scroll down to see the rest.
- Scroll all the way to the top.
- Tap an entry to highlight and reveal it.
- Tap the entry again to copy it.
- Tap the entry again to unhighlight it.
- Scroll all the way to the bottom and notice that some entries are still dimmed.

2022-11-06 11:36 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
> +        this._copied = copied;
```java
_copied = copied;
```

2022-11-06 12:25 UTC, orange-elephant commented
> Some entries seem to stay dimmed after highlighting and copying.

I can't reproduce this on any of my devices, even with 80 entries...
What device is this happening on and how many tokens?

2022-11-06 13:20 UTC, alexbakker commented
I reproduced it on a Pixel 5 and this vault file: https://github.com/beemdevelopment/Aegis/blob/599be443697861bc5dc1606fb16c135aac07ef82/app/src/test/resources/com/beemdevelopment/aegis/importers/aegis_plain.json.

Here's a screenrecording of it happening: https://alexbakker.me/u/qegljxgjrs.mp4

2022-11-12 12:35 UTC, alexbakker approved these changes
Looks good, thanks! We'll merge this after the v2.1 release.

2022-11-20 17:54 UTC, merged