Export vault to HTML
beemdevelopment/Aegis pull request #1039
Opened 2022-11-25 22:33 UTC by CristianAUnisa

Closes #954
I'm marking this as a draft because I'd like to ask if there's a preferred layout or style for the output. This is what I'm getting (zoom decreased to 50%), but it's pretty easy to adjust:

![immagine](https://user-images.githubusercontent.com/31346754/204060425-03d9391b-4c9d-4246-9cb8-ccad2d4f6b51.png)

I'm going to create the test unit when I have more time to focus.

2022-12-03 15:08 UTC, alexbakker requested changes
Thanks for picking this up! The table structure looks good to me. I don't think we should go for the beauty prize, but perhaps the values in the cells could use a little padding and centered placement.

2022-12-03 15:08 UTC, alexbakker commented on app/src/main/res/values/strings.xml
> +    <string name="export_format_html">Web Page (.HTML)</string>
Nit: "Web page (.HTML)"

2022-12-03 15:41 UTC, CristianAUnisa commented
Thank you for the answer. I forgot to ask but an importer is needed too, doesn't it?

2022-12-03 15:43 UTC, alexbakker commented
I don't think we should have an importer for this actually. This is just for people who'd like to have a backup in a format that's easy to print.

2022-12-03 16:22 UTC, CristianAUnisa commented
<img src="https://user-images.githubusercontent.com/31346754/205450526-1b3535f4-6b7f-4a01-a94e-00f5028877de.png" height="100">

Padding set and text centered; I changed the html internal title too. This is something made quickly, but if it needs to look nicer, just let me know (like showing the Favorite value as a checkbox).
I think an importer is needed for creating a test, but I'm going to check if I can put something together without making a mess.

2022-12-04 16:31 UTC, alexbakker commented
Looks good! I wouldn't worry to much about the test. If you want, you can add a basic one where you just run the export and check that it doesn't break. I wouldn't bother with reading the file back, as that's likely going to get messy, like you said.

Now that I've taken a closer look at this, I actually have a couple of extra suggestions:
- Instead of using a ``StringBuilder``, wrap the ``OutputStream`` in a ``PrintStream`` so that we don't have to keep the whole file in-memory.
- Add an ``h1`` to the top of the page with the same "Aegis Authenticator Export" title.

I'd also be happy to merge this as-is and make these small modifications myself afterwards.

2022-12-04 17:46 UTC, CristianAUnisa commented
I'm not knowledgeable about what's needed for Yandex and mOTP, I'm going to take a look but if you want to merge this, I applied the other three suggestions and I decided to make the "Aegis Authenticator Export" a string resource

2022-12-04 22:01 UTC, merged