Add ability to change copy behavior
beemdevelopment/Aegis pull request #1161
Opened 2023-08-15 23:22 UTC by michaelschattgen

In the past we've received a couple different reports (see #1064, #690 and #1120) on how the copy to tap should work in combination with our "tap to reveal" feature. This pull request allows the user to manually set the copy behavior to their liking using the following options:

![image](https://github.com/beemdevelopment/Aegis/assets/7524012/43a95879-fd37-40fb-b3ec-9f2959d8ffbb)

I've also added migration logic to convert the old "copy on tap" boolean to "single tap" to make the update a bit smoother for our users.

This way I hope to please everyone since I've tried to consider everyone's wishes and various situations. Please let me know if you think I've missed anything.

Closes #1064

2023-08-20 11:42 UTC, alexbakker requested changes
Overall this looks good to me, but I did notice one small bug:
- Set up Aegis to copy on single tap and have tap to reveal / tap to highlight enabled
- Tap an entry and notice that it correctly copies the code to the clipboard
- Tap the entry again and notice that the entry doesn't get unhighlighted / the code doesn't get hidden.

2023-08-20 11:42 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/Preferences.java
> +    {
Style nit.

2023-08-20 11:42 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
> +                        {
Style nit.

2023-08-20 11:42 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
> +    {
Style nit.

2023-08-20 13:52 UTC, michaelschattgen commented
Fixed styling issues and the bug you described. Also merged master into this feature branch,

2023-08-20 14:51 UTC, alexbakker approved these changes
LGTM!

2023-08-20 14:51 UTC, merged

2023-08-22 10:21 UTC, D3SOX commented
I don't want to be rude, but is a new release already planned where this change will be included?

2023-08-23 01:33 UTC, michaelschattgen commented
It's not rude, don't worry. We don't like to give ETA's since we work on this in our spare time, that's why we also don't plan ahead when it comes to releases. However we aim to release a beta version this week/next week and hope to release to production soon after depending on the stability.