Replace deprecated startActivityForResult
beemdevelopment/Aegis pull request #1238
Opened 2023-12-03 13:23 UTC by cyb3rko

Hi Aegis team,
this PR can hopefully finally close https://github.com/beemdevelopment/Aegis/issues/807.  
As https://github.com/beemdevelopment/Aegis/pull/998 didn't come to a merge, maybe we can tackle that once again.

Things to discuss:
- Do we want to replace the non-deprecated "Activity.startActivityForResult" as well? It is not marked deprecated in the code as we cast some Activities to an "android.app.Activity" instead of using the original "androidx.appcompat.app.AppCompatActivity". But the issue of best-practice still persists.
  Example: https://github.com/cyb3rko/aegis/blob/9ad3a7925f0e8e980b7eb88ca7cdffbd1c8cb85d/app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java#L492 which is defined here https://github.com/cyb3rko/aegis/blob/9ad3a7925f0e8e980b7eb88ca7cdffbd1c8cb85d/app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java#L308
- Why does the androidTest "testOverall" fail with on error, that does not seem to be connected to intents or something I worked with in this PR? It seems to be connected to group filtering. Stacktrace: https://cdn.cyb3rko.de/Apps/Aegis/testOverall_stacktrace.txt

2023-12-03 14:00 UTC, cyb3rko commented
Ok, the test fails on the master as well.

2023-12-03 14:16 UTC, alexbakker commented
Did you disable all animations on your device/emulator before running the tests? The tests will be flaky with animations enabled.

2023-12-03 14:31 UTC, cyb3rko commented
Oh okay, works now

2023-12-13 10:53 UTC, alexbakker requested changes
Thanks for working on this!

> Do we want to replace the non-deprecated "Activity.startActivityForResult" as well

Yes, let's do that as well.

2023-12-13 10:53 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
> +        if (data == null) return;
We don't shorten if statements like this. Instead:

```java
if (data == null) {
    return;
}
```

Please apply this to the rest of your changes as well.

2023-12-13 11:26 UTC, cyb3rko commented
Alright, working on this

2023-12-21 22:00 UTC, cyb3rko commented on app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> +                _isDoingIntro = false;
Fixed, sorry for the mistake

2023-12-21 22:00 UTC, cyb3rko commented on app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> +                _isAuthenticating = false;
Fixed

2023-12-21 22:00 UTC, cyb3rko commented
Sure, everything's fixed and squashed

2023-12-22 21:39 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> +                _isDoingIntro = false;
No worries. This is what reviews are for!

2023-12-22 21:39 UTC, alexbakker approved these changes
Thanks!

2023-12-22 21:39 UTC, merged