Add audit log
beemdevelopment/Aegis pull request #1357
Opened 2024-04-17 12:52 UTC by michaelschattgen

This pull request is aiming to give more insight to important events that occurred within the app. We chose to use a SQLite database in combination with Room. I've made the choice to only show the entries of the last 30 days for now, but we might want to change that in the future.

The events we're currently tracking are:
- Vault unlocked
- Backup created
- Vault exported
- Entry shared
- Failed vault unlock attempt with password
- Failed vault unlock attempt with biometrics

<img src="https://github.com/beemdevelopment/Aegis/assets/7524012/695d90c5-8f68-4309-bcb6-5b5b830830b2" width=250/>

<img src="https://github.com/beemdevelopment/Aegis/assets/7524012/b3c061c3-9ab5-42d2-aee0-8ae1b386e21b" width=250/>

<img src="https://github.com/beemdevelopment/Aegis/assets/7524012/fc2fbf56-9965-48f0-8356-de65e62dc173" width=250/>

Feel free to comment on this PR if you think we need to track other events.

This is discussed in #1069 and makes it possible to implement #1132.

2024-04-19 03:43 UTC, InfiniteCoder06 commented
@michaelschattgen A small suggestion is to delete the entries greater than 30 days periodically.

2024-04-19 13:19 UTC, alexbakker requested changes
This looks great! I've added a couple of comments.

I think the audit log event types you defined cover most of the important events, but I am missing an event for backups made through ``AegisBackupAgent``. Because Android starts backup agents in a weird restricted mode, this one requires some careful testing to make sure it works correctly.

2024-04-19 13:19 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/views/AuditLogAdapter.java
> +    public void addReferencedEntry(VaultEntry vaultEntry) {
Do we need to separately add the referenced vault entries here? Perhaps we can introduce a ``AuditLogEntryModel`` type that holds the ``AuditLogEntry`` and an optional referenced ``VaultEntry``.

2024-04-19 13:19 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/views/AuditLogHolder.java
> +    private final int initialIconColor;
Style nit.

2024-04-19 13:19 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
> +            _auditLogManager.addVaultUnlockFailedPasswordEvent();
You probably meant to call ``addVaultUnlockFailedBiometricsEvent()`` here. We should probably only log the event if the biometrics prompt was not cancelled by the user.

2024-04-20 22:34 UTC, elliotwutingfeng commented
I like this feature! I think it should also track when the vault password has been changed.

2024-04-20 22:39 UTC, michaelschattgen commented
@elliotwutingfeng I like that! I'm leaving this pull request for what it is (otherwise it will never get done) but that's definitely going on the backlog. Thanks for the suggestion.

2024-05-28 18:54 UTC, alexbakker approved these changes
Very nice!

2024-05-28 18:54 UTC, merged