Clarify FreeOTP+ import needs JSON, not URI-format
beemdevelopment/Aegis pull request #1420
Opened 2024-07-09 17:43 UTC by juleskers

Hi again! After the mini-fix in #1408, I've been toying with FreeOTP+, and syncing it with Aegis.
(Confirming that the FreeOTP+ backup works, after being burned by FreeOTP, never again!)

FreeOTP+ offers two export formats: JSON and URI.
Aegis imports only the JSON, and gives a "cryptic" (for non-developers) "couldn't deserialise java.lang.String to JsonObject" error if you try to import the URI-format.

This PR makes the JSON-format explicit in the importer dropdown, and updates the few translations of the additional-hint-text that I'm personally comfortable with.
I hope your translation community will step up for the rest, but since the dropdown is untranslated, everybody should benefit even without the hint-texts.

I'm not sure if URI-import support is something that is desired. I don't know how generic that format is, or if it is FreeOTP+-specific.
Regardless, I don't have capacity to work on that, but I could open a tracking issue for it, if desired.

2024-07-14 20:36 UTC, alexbakker requested changes
Aegis does support importing a Google Authenticator URI file, but it's not supported when selecting the FreeOTP+ option, so this is a reasonable addition.

Please only change the source string and revert the changes to the translations (these will be overwritten when we import from Crowdin)

2024-07-15 00:24 UTC, juleskers commented
Thanks for the feedback!
I'll update the commit as soon as my young-uns grant me some hobby time 😅

2024-07-15 09:46 UTC, michaelschattgen approved these changes

2024-07-16 15:04 UTC, alexbakker approved these changes
Thanks!

2024-07-16 15:04 UTC, merged