Improve group filters
beemdevelopment/Aegis pull request #1479
Opened 2024-09-10 23:42 UTC by michaelschattgen

This PR moves the group filters from the EntryListView to the MainActivity as shown in the screenshots below.

![image](https://github.com/user-attachments/assets/898e4e41-a25e-4845-953d-6da7704480a7)
![image](https://github.com/user-attachments/assets/22df163b-ce85-4a73-900e-e58e8d92c93f)

Tapping the "All" placeholder group will uncheck all the groups and set the filter to null.
Changing the filter will make a 'Save' button appear at the end of row to set the selected filter as default.

I'm not entirely sure if the "Save" button at the end of the row is intuitive since it will be quite hidden for our users with less screen estate or with a lot of groups, but I think it does the job for now and we can always look into this in the future.

Fixes #1406
Fixes #914

2024-09-12 20:14 UTC, alexbakker requested changes
Very, very nice! A couple of remarks:
- This reintroduces #762. We probably need to move the fix from #1382 to the main activity.
- This essentially reverts ce9a15b7bc2177774c85cdbc77a6e14d90a7b687. Do we still want the ability to filter on "No group"?

2024-09-12 20:14 UTC, alexbakker commented on app/src/main/res/layout/activity_main.xml
> +<LinearLayout
Could you fix the indentation here?

2024-09-15 17:31 UTC, alexbakker requested changes
I think we're missing an ``updateDividerDecoration()`` call somewhere. When adding a couple of entries, the offset between entries is missing:

![image](https://github.com/user-attachments/assets/f8c40cc2-9663-40b1-a56a-32165d154bc7)

2024-09-16 21:47 UTC, alexbakker approved these changes

2024-09-16 21:47 UTC, merged

2024-09-16 23:29 UTC, tiniwings commented
Pill group click should be an automatic selection of that category like radio box selection.

Click on Work, it should automatically show only Work group.

Click on Games, it should now show only Games group.. Like a filter.

Clicking on All will clear all filter and shows everything.

By this way its easy to switch between the groups with one click.

2024-09-18 21:43 UTC, michaelschattgen commented
@tiniwings thanks for chiming in. The way I implemented this is just like in the screen share you mentioned. After your comment and bazzik's comment over at https://github.com/beemdevelopment/Aegis/issues/914#issuecomment-2354110271 we decided to change the pills to a 1-tap in our next update since our users probably prefer it that way. Maybe in the future we will allow multi-select by long pressing but that's not a high priority right now.

Will have updates on this soon.