Improve search feature for better UX
beemdevelopment/Aegis pull request #1545
Opened 2024-11-24 23:27 UTC by michaelschattgen

This PR improves the search feature as requested in #1527 and #1536. After this gets merged Aegis will:

1. Hide the group chips when user starts searching
2. Ignore the current active group filter
3. Matches now in all fields that are enabled to search in

Example: 

| Search Filter     | Issuer   | Name   | Match? |
|--------------------|----------|--------|--------|
| `GitHub michaelschattgen`     | GitHub   | michaelschattgen   | ✅ Yes  |
| `GitHub`          | GitHub   | michaelschattgen   | ✅ Yes  |
| `michaelschattgen`            | GitHub   | michaelschattgen   | ✅ Yes  |
| `hub michaelschattgen`        | GitHub   | michaelschattgen   | ✅ Yes   |
| `michaelschattgen Git`     | GitHub   | michaelschattgen   | ✅ Yes  |
| `Github e`         | GitHub   | michaelschattgen   | ✅ Yes    |
| `GitHub michaelschattgen 1`| GitHub   | michaelschattgen   | ❌ No   |
| `hub z`             | GitHub   | michaelschattgen   | ❌ No   |

2024-11-25 19:12 UTC, alexbakker requested changes
Neat. One minor issue: The chip group does not become visible again if the search is cancelled with the X button.

2024-11-25 21:54 UTC, alexbakker approved these changes

2024-11-25 21:54 UTC, merged

2024-11-25 22:03 UTC, ivancarlosti commented
Updated app, looks like partial words search is not working :/

2024-11-25 22:04 UTC, michaelschattgen commented
We've merged this 10 minutes ago. The feature will be available in our next release.

2024-12-03 00:42 UTC, Gammachange commented
@michaelschattgen Hi there,
I just wondering this its bug or somthing, that `the 
Group filter` still visible when keybaord Pop-up 

See here  the defreen between the public, and the "dev" version , when the app its open
The new release: 3.3.2 - _**here the Group its visible**_ 
![Screenshot_20241203_002301](https://github.com/user-attachments/assets/a268b387-bb24-473f-8f8e-1a77a95dd27e)

> 
" agisbev : 3.3.1-d48f2ea (master) - _**and here its no't.**_
![Screenshot_20241203_002404](https://github.com/user-attachments/assets/217ea368-781c-4247-b218-bad940593670)

Thanks again for your'e time!

2024-12-03 00:46 UTC, michaelschattgen commented
Are you completely sure you're actually running 3.3.2? Could you please double check this? Either through Aegis' about page or your device settings.

I just updated to 3.3.2 through the Google Play Store and it hides the group filter upon opening search for me (which is the intended behaviour).

2024-12-03 00:55 UTC, Gammachange commented
Yes, i download the new version from google play store about 2h new
![Screenshot_20241203_004741](https://github.com/user-attachments/assets/a1700adf-b315-4b5d-a2ef-bf1e3e4ec89a)
Just to be sure , i am no't messing somthing , when you open the the "Groube filter still visible "  but when you , close the search, let say go to `setting and open is again, new its work 

Like this 
![Screenshot_20241203_005446](https://github.com/user-attachments/assets/7d08e0c3-f130-40df-b83e-d75ccac6ca5a)

2024-12-03 01:00 UTC, michaelschattgen commented
Ah sorry, i see it now. I assume you have 'Focus search on start' enabled, this causes the group filter to not properly hide due to a race condition. Will fix it sometime later this week, thanks for letting us know!

2024-12-03 01:33 UTC, Gammachange commented
@michaelschattgen Hi
 i have new thing that can help you, " the isuss its becaus the app lock" (boiomatrics/password etc.
When you set the app lock to "non" its work,  I hope this helps.