Option to Disable Automatic Refresh for Selected Code
beemdevelopment/Aegis pull request #791
Opened 2021-07-28 11:15 UTC by bitscuity

I implemented the pause feature discussed in #789.

You can enable this new feature in the settings menu under "Behavior" > "Freeze tokens when tapped". I tested it a bit and everything works as I would like it to.

Things that I'm not quite sure of:
- Explanation in settings might not be the best to describe what the feature does?
- Maybe we should add an icon next to a frozen token to inform the user that the token is outdated/paused?

What do you think?

2021-07-31 10:27 UTC, alexbakker requested changes
Thanks for the patch! I expected this to be a bit more work, but it seems that you found a clever way to implement this.

I would suggest disabling the preference (as in, make the setting unchangeable) for this as long as "highlight tokens when tapped" and/or "tap to reveal" is not enabled. This makes it clear to the user that the setting has no effect until at least one of those two is enabled.

Regarding the two things you're weren't sure about:
- Sounds clear enough to me!
- Since this feature is disabled by default, I'm not too worried about users getting surprised that the token refresh is paused. So I don't think an indicator is necessary here.

2021-08-01 18:18 UTC, bitscuity commented
There you go

2021-08-10 09:12 UTC, alexbakker commented
Looks good! Could you squash everything into a single commit?

2021-08-10 10:39 UTC, bitscuity commented
First time squashing commits in git, hope I didn't mess it up :sweat_smile:

2021-08-11 11:26 UTC, alexbakker commented
It looks like you also squashed 6bafd9e9ae0a91add9f0fb335dedf19224987715 and 74e460d9a998b45a002b6c1791f44cc2220874ff into this by accident.

2021-08-11 12:05 UTC, bitscuity commented
Fixed it

2021-08-11 12:28 UTC, alexbakker approved these changes
Thanks!

2021-08-11 12:28 UTC, merged