Add DUO importer
beemdevelopment/Aegis pull request #835
Opened 2021-10-27 21:17 UTC by anibyl

Hey there!

This PR adds [DUO Mobile](https://play.google.com/store/apps/details?id=com.duosecurity.duomobile) OTP importer.

PS: I added translations in the languages I knew; please let me know if it's not the right way of contributing translations.

#68

2021-10-30 09:09 UTC, alexbakker requested changes
Thanks for working on this! It'll take me a couple of days before I can get my hands on a rooted device again, so I can't test this immediately, but here are some initial comments.

2021-10-30 13:23 UTC, anibyl commented on app/src/main/java/com/beemdevelopment/aegis/importers/DuoImporter.java
> +                    @NonNull JSONObject entry = _array.getJSONObject(i);
This is something we use at work. Removed.

2021-10-30 13:28 UTC, anibyl commented on app/src/main/java/com/beemdevelopment/aegis/importers/DuoImporter.java
> +                    counter = otpData.getLong("counter");
Mostly my unfamiliarity with org.json library.
I wanted to use `#optLong(String, long)` but it receives a primitive as a fallback which is unacceptable: I need a nullable variable.
Replaced with `#has` and `#getLong`.

2021-11-28 19:35 UTC, anibyl commented
Hi! How's your search for a rooted device going?

2021-12-01 11:48 UTC, alexbakker commented
Yes, works well! Could you squash everything into a single commit? I'll merge this afterwards.

2021-12-01 14:54 UTC, Hacker437 commented
> Yes, works well! Could you squash everything into a single commit? I'll merge this afterwards.

@alexbakker I think you can squash when merging 🤔?

2021-12-02 09:12 UTC, alexbakker commented
Yes, but "squash and merge" performs a fast-forward merge instead of creating a merge commit. I'd like to keep things consistent.

2021-12-02 15:39 UTC, Hacker437 commented
> Yes, but "squash and merge" performs a fast-forward merge instead of creating a merge commit. I'd like to keep things consistent.

Ohho ok.

2021-12-03 03:19 UTC, anibyl commented
> Yes, works well! Could you squash everything into a single commit? I'll merge this afterwards.

Done.

2021-12-04 10:09 UTC, alexbakker approved these changes
Thanks!

2021-12-04 10:09 UTC, merged