WIP: Add Bitwarden importer
beemdevelopment/Aegis pull request #908
Opened 2022-04-13 09:26 UTC by CristianAUnisa

2022-04-13 09:34 UTC, CristianAUnisa commented
@alexbakker import from a JSON file is already working, I still need to create tests for it; as reported in the linked issue, encrypted json files from Bitwarden should be unimportable (for now).
I'm going to start working on the csv format, but I'd like to ask you a couple of questions:

- Do you think that we should have two separate options on the importer selector (one for the JSON format, the other one for the CSV) or should the app recognise the right format automatically?
- Do you think it would be worth to add a CSV parser library to Aegis? I can work around it in this case but I was wondering if a parser would be useful in the future

2022-04-15 17:22 UTC, CristianAUnisa commented
Steam account URIs are prefixed by `steam:// `
https://bitwarden.com/help/authenticator-keys/#steam-guard-totps

I made a custom test for this case

2022-04-21 18:08 UTC, alexbakker requested changes
Nice work! Just a couple of comments.

2022-04-21 18:08 UTC, alexbakker commented on app/src/main/res/values/strings.xml
> +    <string name="importer_help_bitwarden">Supply a Bitwarden export/backup file.</string>
Could you add a note at the end that says: "Encrypted files are not supported".?

2022-04-22 19:06 UTC, CristianAUnisa commented
Just committed your suggestions, let me know if you spot anything wrong! I run the tests again and everything is working.

2022-04-24 09:44 UTC, alexbakker commented
Looks good, thanks! Could you squash your changes into a single commit?

2022-04-24 14:58 UTC, CristianAUnisa commented
Done!

2022-04-27 10:58 UTC, CristianAUnisa commented
I remembered there's a section in the readme file listing supported apps for the importing feature; Bitwarden can be listed when there's a new release

2022-04-30 11:13 UTC, alexbakker approved these changes
Thanks!

2022-04-30 11:13 UTC, merged

2023-04-15 13:38 UTC, devnoname120 commented
@CristianAUnisa I tried to import from CSV and the importer fails on any TOTP that doesn't explicitly specify the protocol, even though it's optional in Bitwarden.

```
com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null

com.beemdevelopment.aegis.importers.DatabaseImporterEntryException: com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null
```

2023-04-15 18:24 UTC, CristianAUnisa commented
Is Bitwarden using the TOTP protocol as the default one when none is specified?

2023-04-15 20:27 UTC, devnoname120 commented
@CristianAUnisa I can confirm:

> By default, Bitwarden will generate six-digit TOTPs using SHA-1 and rotate them every 30 seconds

([source](https://bitwarden.com/help/authenticator-keys/#:~:text=By%20default%2C%20Bitwarden%20will%20generate,URI%20for%20your%20vault%20item.))