When the text is empty, the generated TextDrawable uses a grey bgcolor
beemdevelopment/Aegis pull request #956
Opened 2022-08-06 02:18 UTC by Hovn

When the text is empty, the generated TextDrawable uses a grey bgcolor.
This will help remind customers that this is where an icon is selected.
I wanted to use arrays.xml/colors.xml to manage the colors at first, but after looking at the source code(The color generator is also hardcoded, so I followed), I used a hardcoded way. Because the current TextDrawableHelper.java does not have a Context to load resources.

This is a suggested change, please evaluate.

Effect:
![image](https://user-images.githubusercontent.com/6801952/183229634-12c74850-1738-4cf4-9d95-bdad6ff667e4.png)

2022-08-08 18:54 UTC, alexbakker requested changes
I'm a fan of this idea, but I think the color you picked is far too bright in dark mode. I suggest grabbing one of the existing colors from `attrs.xml`.

With regards to the Context, you should be able to obtain it from the view: ``view.getContext()``.

2022-08-23 07:49 UTC, Hovn commented
Yes, the same color value is used in both modes. I will revise it later. 
By the way: the colors of _generator(in TextDrawableHelper), I think it can also be managed by xml. Would this be a better way?
like this:
`List<Integer> bg_colors=Arrays.stream(view.getResources().getIntArray(R.array.text_drawable_colors)).boxed().collect(Collectors.toList());`
`ColorGenerator _generator = ColorGenerator.create(bg_colors);`

2022-09-05 16:39 UTC, alexbakker commented
Yeah, let's do that.

2022-12-24 17:25 UTC, alexbakker commented
What's the status here?

2023-08-16 14:54 UTC, alexbakker commented
Since there hasn't been activity here for a while, I'm closing this one to clean the up the list of open pull requests a bit.

2023-08-16 14:54 UTC, closed without merging