Minimize or Close app after copying OTP #805
beemdevelopment/Aegis pull request #969
Opened 2022-08-26 18:56 UTC by digitalheir

2022-09-14 14:46 UTC, alexbakker requested changes
Thanks for implementing this. I've left a couple of comments.

2022-09-14 14:46 UTC, alexbakker commented on app/src/main/res/xml/preferences_behavior.xml
> +        android:summary="Minimize app after copying token"
This should to be a translatable string as well. Also, slight modification suggestion: "Minimize the app after copying a token".

2022-09-14 14:46 UTC, alexbakker commented on app/src/main/res/values/strings.xml
> +    <string name="pref_minimize_on_copy_title">Minimize app after copying token</string>
Let's make the title a bit shorter, and the summary a bit longer. For the title: "Minimize on copy".

2022-09-14 14:46 UTC, alexbakker commented on app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> +        if(_entryListView.isMinizeAfterCopyEnabled()) {
I don't think the EntryListView needs to know about this. We can simply check for ``_prefs.isMinimizeOnCopyEnabled()`` here.

Also, missing a space after ``if`` here.

2022-09-14 14:46 UTC, alexbakker commented on app/src/main/res/values-ar-rSA/strings.xml
>      <string name="preference_manage_groups_summary">أدر واحذف مجموعاتك هنا</string>
Please remove the translations to other languages. All translations are managed in Crowdin and the ones you've added here would be overwritten when we import them before the next release.

2022-09-17 12:43 UTC, alexbakker requested changes
Looks good. Please also remove the translations to other languages and squash your commits. After that, this'll be good to go!

2022-09-17 15:05 UTC, digitalheir commented
I don't know how to squash commits

2022-09-17 15:55 UTC, alexbakker commented
No problem. It's easy to learn though! There are lots of good articles about this online. Rebasing is also a good tool to have in your toolbox. As you've probably noticed, merging things back into your branch gets messy fairly quickly.

2022-09-17 15:55 UTC, alexbakker approved these changes
Thanks!

2022-09-17 15:55 UTC, merged

2026-04-12 14:13 UTC, juke32 commented
How about having it go to the last used app, the screen most likely to need the OTP after copy

2026-04-13 09:45 UTC, cacfd3a commented
If you open Aegis while another app is on the foreground (like from a shortcut in the Quick Settings panel), it should already work like this.

In general, this is a responsibility of the operating system. I think apps cannot even query what is the most recently used app, because that is a pretty serious privacy and security risk.

2026-04-13 11:02 UTC, michaelschattgen commented
>I think apps cannot even query what is the most recently used app

Correct. We are technically able to assign an app to each entry so that Aegis launches that app, but that will just launch a new intent. This will confuse users and they'll lose their current sign-in progress of said app.