Added checks for animations accessibility
beemdevelopment/Aegis pull request #994
Opened 2022-10-02 13:51 UTC by MasterReach1

Per issue from lucy, added checks for Remove Animations in accessibility settings for a bug fix.

2022-10-02 13:52 UTC, MasterReach1 commented
Please review and provide any feedback.

2022-10-05 11:20 UTC, alexbakker requested changes
Thanks for picking this up.

Couple of points of feedback:
- I actually still see an animation the first time I open the app. After locking and then unlocking the app, the animation is gone.
- Let's place this check inside the ``runEntriesAnimation`` function, so that we don't have to add this check everywhere we might call this function in the future.
- If you pass a default to the ``getFloat`` function, there's no exception thrown in case the setting doesn't exist. So:

    ```java
    if (Settings.Global.getFloat(requireContext().getContentResolver(), Settings.Global.ANIMATOR_DURATION_SCALE, 1f) != 0f) {
        ...
    }
    ```
- This actually doesn't address the issue fully, because there are still other places in the app where we have animations:
  - Navigating through preferences triggers a transition animation
  - Long pressing an entry triggers an icon animation

  I'm also fine with merging this as a partial fix, though.

2022-10-05 12:46 UTC, MasterReach1 commented
Thank you for the feedback. I will make the requested changes to the best of my efforts and commit them to my branch.

I have moved the check to runEntriesAnimation as requested, and the rest is underway. If you choose to merge this as a partial fix, I can upload another PR with the other changes requested. However, I would rather wait to get it all right first so the merge can be of good quality.

2022-10-06 01:52 UTC, MasterReach1 commented
I have made the requested changes. When the "Remove Animations" accessibility option is enabled, the list does not animate in at any point. Preference navigation is no longer animated, and long presses are not either. I tested with the accessibility option disabled, and everything animates as intended. 

Please provide any feedback if needed.

2022-10-08 10:09 UTC, alexbakker commented
Thanks. Couple more things:
- Upon initial unlock of the app, the entry list animation is still played.
- There are a couple of files with unneeded changes, like ``MainActivity.java`` and ``EntryListView.java``. Please revert those.
- Please squash your work into a single commit.

> I don't know why, but "Task :app:connectedDebugAndroidTest" keeps failing in the build test runs on GitHub.

Unfortunately the instrumented tests are very flaky on GitHub. As long as they complete successfully on your local machine, it's fine.

2022-12-24 17:25 UTC, alexbakker commented
What's the status here?

2023-08-16 14:54 UTC, alexbakker commented
Since there hasn't been any activity here for a while, I'm closing this one to clean the up the list of open pull requests a bit.

2023-08-16 14:54 UTC, closed without merging